name: 🚀 Deploy to Production

on:
  push:
    branches:
      - main
    paths:
      - 'app/public/wp-content/themes/acm-irving/**'

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: app/public/wp-content/themes/acm-irving/
          server-dir: /public_html/wp-content/themes/acm-irving/
          exclude: |
            **/.git*
            **/.git*/**
            **/.DS_Store
            **/node_modules/**
